// Copyright (c) 2018, Peter Ohler, All rights reserved.

#ifndef __AGOO_PUB_H__
#define __AGOO_PUB_H__

#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

struct _Text;

typedef enum {
    PUB_SUB	= 'S',
    PUB_CLOSE	= 'C',
    PUB_UN	= 'U',
    PUB_MSG	= 'M',
    PUB_WRITE	= 'W',
} PubKind;

// Generated by extened handlers and placed on the pub_queue to be pulled off
// in the con_loop.
typedef struct _Pub {
    struct _Pub		*next;
    PubKind		kind;
    bool		bin;
    uint64_t		cid;
    char		*subject;
    union {
	uint64_t	sid;
	struct _Text	*msg;
    };
} *Pub;

extern Pub	pub_close(uint64_t cid);
extern Pub	pub_subscribe(uint64_t cid, uint64_t sid, const char *subject);
extern Pub	pub_unsubscribe(uint64_t cid, uint64_t sid);
extern Pub	pub_publish(char *subject, const char *message, size_t mlen, bool bin);
extern Pub	pub_write(uint64_t cid, const char *message, size_t mlen, bool bin);

#endif // __AGOO_PUB_H__
